<!doctype html>
<html lang="ru">

<?php include(__DIR__ . '/../layout/head.phtml') ?>

<body class="min-vh-100 d-flex flex-column">
    <?php include(__DIR__ . '/../layout/header.phtml') ?>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <tbody>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>Последняя проверка</th>
                            <th>Код ответа</th>
                        </tr>
                        <?php foreach ($urls as $url) : ?>
                            <tr>
                                <td><?= $url['url_id'] ?></td>
                                <td><a href="<?= $router->urlFor('url', ['id' => $url['url_id']]) ?>"><?= $url['url_name'] ?></a></td>
                                <td><?= $url['url_last_check'] ?></td>
                                <td><?= $url['url_last_status_code'] ?></td>
                            </tr>
                        <?php endforeach ?>

                    </tbody>
                </table>
            </div>
        </div>
    </main>

    <?php include(__DIR__ . '/../layout/footer.phtml') ?>

</body>

</html>