{% extends 'layout/layout.phtml' %}

{% block content %}

<div class="container-lg mt-3">
    <h1>Сайты</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
            <tbody>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Последняя проверка</th>
                    <th>Код ответа</th>
                </tr>
                {% for url in urls %}
                    <tr>
                        <td>{{ url.url_id }}</td>
                        <td><a href="{{ router.urlFor('url', {'id': url.url_id}) }}">{{url.url_name}}</a></td>
                        <td>{{ url.url_last_check }}</td>
                        <td>{{ url.url_last_status_code }}</td>
                    </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}
