<!doctype html>
<html lang="ru">

<?php include('head.phtml') ?>

<body class="min-vh-100 d-flex flex-column">
    <?php include('header.phtml') ?>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1></h1>
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <h1 class="display-3">Анализатор страниц</h1>
                    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                    <form action="/urls" method="post" class="row">
                        <div class="col-8">
                            <?php if (empty($errors)) : ?>
                                <input type="text" name="url[name]" value="<?= $url['name'] ?>" class="form-control form-control-lg" placeholder="https://www.example.com">
                            <?php else : ?>
                                <input type="text" name="url[name]" value="<?= $url['name'] ?>" class="form-control form-control-lg is-invalid" placeholder="https://www.example.com">
                                <div class="invalid-feedback">
                                    <?php foreach ($errors as $message) : ?>
                                        <div><?= $message ?></div>
                                    <?php endforeach ?>
                                    <!-- <?php var_dump($errors) ?> -->
                                </div>
                            <?php endif ?>
                        </div>
                        <div class="col-2">
                            <input type="submit" class="btn btn-primary btn-lg px-5 mx-3 text-uppercase" value="Проверить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

    <?php include('footer.phtml') ?>
</body>

</html>