<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1></h1>
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <h1 class="display-3">Анализатор страниц</h1>
                    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                    <form action="/urls" method="post" class="row">
                        <div class="col-8">
                            <?php if (empty($errors)) : ?>
                            <input type="text" name="url[name]" value="<?= $url['name'] ?>"
                                class="form-control form-control-lg" placeholder="https://www.example.com">
                            <?php else : ?>
                            <input type="text" name="url[name]" value="<?= $url['name'] ?>"
                                class="form-control form-control-lg is-invalid" placeholder="https://www.example.com">
                            <div class="invalid-feedback">
                                <?php foreach ($errors as $errorTypes) : ?>
                                    <?php foreach ($errorTypes as $errorMessage) : ?>
                                        <div><?= $errorMessage ?></div>
                                    <?php endforeach ?>
                                <?php endforeach ?>
                                <!-- <?php var_dump($errors) ?> -->
                            </div>
                            <?php endif ?>
                        </div>
                        <div class="col-2">
                            <input type="submit" class="btn btn-primary btn-lg px-5 mx-3 text-uppercase"
                                value="Проверить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>
</body>

</html>